// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403044416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampeaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("Reliquia1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Reliquia2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Reliquia3Id")
                        .HasColumnType("integer");

                    b.Property<int>("TipoBuildId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampeaoId");

                    b.HasIndex("Reliquia1Id");

                    b.HasIndex("Reliquia2Id");

                    b.HasIndex("Reliquia3Id");

                    b.HasIndex("TipoBuildId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("backend.Models.Campeao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<string>("Bonus")
                        .HasColumnType("text");

                    b.Property<string>("Carta1")
                        .HasColumnType("text");

                    b.Property<string>("Carta2")
                        .HasColumnType("text");

                    b.Property<string>("Estrelas")
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Regiao1")
                        .HasColumnType("text");

                    b.Property<string>("Regiao2")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Campeoes");
                });

            modelBuilder.Entity("backend.Models.MensagemRecrutador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("MensagensRecrutadores");
                });

            modelBuilder.Entity("backend.Models.Modificador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Raridade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Modificadores");
                });

            modelBuilder.Entity("backend.Models.Reliquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Imagem")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Raridade")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reliquias");
                });

            modelBuilder.Entity("backend.Models.TipoBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposBuilds");
                });

            modelBuilder.Entity("backend.Models.Build", b =>
                {
                    b.HasOne("backend.Models.Campeao", "Campeao")
                        .WithMany("Builds")
                        .HasForeignKey("CampeaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Reliquia", "Reliquia1")
                        .WithMany()
                        .HasForeignKey("Reliquia1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Reliquia", "Reliquia2")
                        .WithMany()
                        .HasForeignKey("Reliquia2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Reliquia", "Reliquia3")
                        .WithMany()
                        .HasForeignKey("Reliquia3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.TipoBuild", "TipoBuild")
                        .WithMany("Builds")
                        .HasForeignKey("TipoBuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campeao");

                    b.Navigation("Reliquia1");

                    b.Navigation("Reliquia2");

                    b.Navigation("Reliquia3");

                    b.Navigation("TipoBuild");
                });

            modelBuilder.Entity("backend.Models.Campeao", b =>
                {
                    b.Navigation("Builds");
                });

            modelBuilder.Entity("backend.Models.TipoBuild", b =>
                {
                    b.Navigation("Builds");
                });
#pragma warning restore 612, 618
        }
    }
}
